ftr: error page for unauthorized users or page not found
catenax-ng/tx-traceability-foss-frontend pull request #18
Opened 2023-02-23 08:16 UTC by ds-ext-dskrzypczak

TRACEFOSS-859

2023-02-27 09:00 UTC, evia-fbedarf requested changes

2023-02-27 09:00 UTC, evia-fbedarf commented on src/app/modules/page/error-page/presentation/error-page.component.ts
> +  public title: string = 'errorPage.title';
Put these translations keys into the html, and change the logic that it is done in the HTML.
Text-specific stuff should be handled in the HTML no in the code.

2023-02-27 09:00 UTC, evia-fbedarf commented on src/app/modules/page/error-page/presentation/error-page.component.html
> +<div class="error-page-container">
Is it possible to create a reusable component out of that? So we can reuse them later in other pages, if for example data fails to load for a table or something.

2023-02-27 09:00 UTC, evia-fbedarf commented on src/app/modules/page/error-page/presentation/error-page.component.spec.ts
> +    await fixture.whenStable();
What does this do?

2023-02-28 08:21 UTC, ds-ext-dskrzypczak commented on src/app/modules/page/error-page/presentation/error-page.component.spec.ts
> +    await fixture.whenStable();
https://angular.io/api/core/testing/ComponentFixture#whenStable

I've found out that it helps a lot if you need to wait for some async activity.

2023-02-28 10:02 UTC, ds-ext-dskrzypczak commented on src/app/modules/page/error-page/presentation/error-page.component.html
> +<div class="error-page-container">
Yeah, I remember our discussion to be able to do it in the future. I have been thinking about that, and I think the better approach is to implement it in separate task for given example and purpose. It shouln't take much time to adapt the code.

2023-02-28 10:57 UTC, evia-fbedarf approved these changes

2023-02-28 12:20 UTC, merged